[project]
name = "cade-task"
version = "0.4.2"
description = "A loose wrapper around reminders-cli"
readme = "README.md"
authors = [
    { name = "Cade Ekblad-Frank", email = "cade@e-f.me" }
]
requires-python = ">=3.13"
dependencies = [
    "typer>=0.15.2",
]

[dependency-groups]
dev = [
    "devtools>=0.12.2",
    "ipython>=9.1.0",
    "mypy>=1.15.0",
    "pytest>=8.3.5",
    "pytest-cov>=6.1.1",
    "pytest-mock>=3.14.0",
    "ruff>=0.11.5",
]
docs = [
    "myst-parser>=4.0.1",
    "pygments>=2.19.1",
    "sphinx>=8.2.3",
    "sphinx-autobuild>=2024.10.3",
    "sphinx-autodoc-typehints>=3.1.0",
    "sphinx-copybutton>=0.5.2",
    "sphinx-press-theme>=0.9.1",
]

[project.urls]
Repository = "https://github.com/cadeef/cade-task"
Documentation = "https://task.cade.pro"

[project.scripts]
task = "cade_task.cli:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
# https://docs.astral.sh/ruff/rules/
lint.select = [
    "B",
    "E",
    "F",
    "I",
    "C4",  # List comprehensions
    # "FIX",  # TODO, FIX, etc
    "LOG",  # Logger bugs
    "PT",  # Pytest
    "RET",  # Returns
    "SIM",  # Simplify
    "RUF",  # Ruff-specific
]
lint.ignore = [
    # "B904",  # Allow raising exceptions without from e, for HTTPException
]
line-length = 120
